http:
  address: 127.0.0.1:8080
  tls:
    address: 127.0.0.1:8443
    cert: /Users/jan/vagrant/schild/ssl/bestbytes_net.crt
    key: /Users/jan/vagrant/schild/ssl/bestbytes_net.key
  basicauthfile: /Users/jan/go/src/github.com/foomo/dumpster/examples/users
datadir: /private/tmp
remotes:
    myself:
        endpoint: http://127.0.0.1:8080
dumps:
  dumpster:
    dump:
      program: /Users/jan/go/src/github.com/foomo/dumpster/examples/files/dump.sh
      args:
        - /Users/jan/go/src/github.com/foomo/dumpster
    restore:
      program: tar
      args:
        - -tzvf
  caproxy:
    dump:
      program: /Users/jan/go/src/github.com/foomo/dumpster/examples/files/dump.sh
      args:
        - /Users/jan/go/src/git.bestbytes.net/CA-Proxy
